language: node_js
node_js:
- '8'
- '7'
- '6'
env:
- MONGODB_CONNECTION_STR=mongodb://travis:test@127.0.0.1:21686/mydb_test APP_BASE_URL=http://localhost:5000 EMAIL_ENABLED=false
cache:
  directories:
  - node_modules
services:
- mongodb
before_script:
- sleep 15
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
- mongo mydb_test --eval 'db.users.insert({_id:"abc123",username:"Player1",email:"player1@email.com"});db.users.insert({_id:"def456",username:"Player2",email:"player2@email.com"});'
